name: Plint
description: >-
  Lint project with pylint.
  Projects must specify pylint as a dependency.

inputs:
  cache:
    description: Whether to cache project dependencies.
    required: false
    default: "true"
  package_manager:
    description: The package manager to use ("poetry" or "uv").
    required: false
    default: uv
  python_version:
    description: The python version to use in SemVer range syntax.
    required: false
    default: "3.13"
  working_directory:
    description: The directory to execute commands in.
    required: false
    default: "."

outputs: {}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Install python
      uses: lojoja/action-setup-python-env@main
      with:
        cache: ${{ inputs.cache }}
        package_manager: ${{ inputs.package_manager }}
        python_version: ${{ inputs.python_version }}
        working_directory: ${{ inputs.working_directory }}

    - name: Run pylint
      run: ${{ inputs.package_manager }} run pylint --recursive=y .
      shell: bash
      working-directory: ${{ inputs.working_directory }}
